language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create db:structure:load db:test:prepare

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec